# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
script:
  - cd ..
  - cp -r TestFIGlet FIGlet
  - cd FIGlet
  - julia --color=yes --project -e 'using Pkg; Pkg.build(); Pkg.test()'
